name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: uname -v
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: My first custom script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh | sh
